apiVersion: v1
kind: Namespace
metadata:
  name: lab-shop
  labels:
    k8sboard.io/lab: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: lab-batch
  labels:
    k8sboard.io/lab: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: lab-broken
  labels:
    k8sboard.io/lab: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: lab-quota
  labels:
    k8sboard.io/lab: "true"
